# Generated by Django 2.1.7 on 2019-03-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='course_name',
        ),
        migrations.AddField(
            model_name='person',
            name='course',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
