# Generated by Django 2.1.7 on 2019-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default='1994-06-11'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='fname',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
    ]
